pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- bash: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build 
    python -m pip install --upgrade twine 
    python -m pip install --upgrade setuptools 
    python -m pip install --upgrade wheel 
    python -m pip install find_packages
    python -m pip install findspark 
    python -m pip install pytest
  displayName: 'Install and upgrade pip setuptools and wheel'

- bash: |
    python -m pip install -r requirements.txt -U
  displayName: 'Install dependencies for build'

- bash: |
    cd tests 
    python -m pytest test_PyTools.py
    python -m pytest test_SparkTools.py
  displayName: 'Unit Testing'
      # workingDirectory: .

- bash: |
    py -m build
  displayName: 'Building AttributeBoss'
  # workingDirectory: .

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: BossFeed # For an organization-scoped feed, artifactFeed: <FEED_NAME>
  displayName: 'Twine Authenticate'

# 
- bash: |
    twine upload -r BossFeed --config-file $(PYPIRC_PATH) dist/* 
  displayName: 'Upload to feed'
