# define some variables for later use
variables:
  pythonVersion: 3.10
  artifactFeed: ab-feed

trigger:
  branches:
    include:
    - main

pr:
- none

pool:
  vmImage: ubuntu-latest

jobs:
- job: Build
  steps:
  - task: UsePythonVersion@0
    displayName: Use Python $(pythonVersion)
    inputs:
      versionSpec: $(pythonVersion)

  - bash: python -m pip install --upgrade pip
    displayName: Install and upgrade pip

  - bash: |
      python -m pip install -r requirements.build.txt -U 
      python -m pip install -r requirements.txt -U
    displayName: Install packages for build

  - bash: |
      cd tests 
      python -m pytest test_features.py
      python -m pytest test_standardize_attributes.py 
      python -m pytest test_extract_attributes.py 
    displayName: 'pytest'

  - bash: |
      # Read the current version number from the version file
      current_version=$(cat version)
      # Generate a new version number
      new_version=$(echo $current_version | awk -vFS=. -vOFS=. '{$NF+=1; print $0}')
      # Compare the current and new version numbers
      if [[ "$current_version" != "$new_version" ]]; then
        echo "Version has changed. Building artifacts..."
        # Update the version file with the new version number
        echo $new_version > version 
        python -m build
      else
        echo "Version has not changed. Skipping artifact build."
      fi
    displayName: Check and Build Package
    workingDirectory: .

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: ab-feed

  - bash: python -m twine upload -r ab-feed --config-file $(PYPIRC_PATH) dist/*.whl
    displayName: Upload artifacts
