[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=67", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[project]
name = "AttributeBoss"
version = "0.0.1"
authors = [{ name="BDRUMMOND", email="b3drumms@gmail.com" },]

description = "A package to prep data for more advanced preprocessing or transformations"
readme = "README.md"
requires-python = ">=3.10"

license = {file = "LICENSE"}

classifiers = [
    "Programming Language :: Python :: 3"
]

[project.urls]
Home = "https://dev.azure.com/gocloudclient0099/LPA/_git/AttributeBoss"